### ISSUE TITLE
Excellent way of using conrod

### ISSUE THREAD

**Issue by LeonGGX** [mpizenberg/computer-vision-rs#2]
Thanks for this excellent work which makes using conrod much easier ...

There seems to be a problem when closing the prog window.
Here is the error message I receive when closing the program :
thread 'main' panicked at 'Failed to close input method: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 14, minor_code: 0 }', libcore/result.rs:945:5

Working on ubuntu 18.04
gnome - x11

**Comment by mpizenberg** [comment]
The problem when closing the program is not related to my `Program` little experience. It happens also with default conrod examples. I'm still a Rust beginner and this whole repository is just my sandbox for experimentations so I didn't really care about that.

I suggested this approach in an [issue on conrod](https://github.com/PistonDevelopers/conrod/issues/1182), and turns out conrod used to have similar things in the past, and prefer to stay backend agnostic from now on. But in an answer, mitchmindtree pointed me to a recent project called [nannou](https://github.com/nannou-org/nannou) which does something like this. I've not tested yet but pretty sure it will interest you.

Thanks for your interest @LeonGGX, I'll close this issue since there is not much else to say. I hope this will help you. Cheers
